### PR TITLE
Barcode improvements

### PR DESCRIPTION
**Pull request by Guusggg**
#63 
#66 

Hi,

This is my first pull request and first time working with Flutter. I think I got the hang of it, however my code quality is not very high. I nest a lot of dialog functions and I omit a lot of error checking currently. I also burst the server with API calls and I'm willing to take feedback how to reduce the strain. (Although I didn't notice any issues with the development server running locally here, so far) I was hoping someone could review or otherwise change my code to the quality of this repository. 

That said, I implemented the following features:
- [x] Scan any barcode, and receive a popup to Receive it as a line item from a purchase order
        1. Scan any barcode
        2. Click on Receive item
        3. Select the Part that you identified it as (This pulls all purchase orders and looks for unique Parts that are waiting to be received)
        4.1. If the Part occurs in multiple Purchase Orders, a dialog will ask you which one of the PurchaseOrders you want to receive to.
        4.2. If the Part is only in one PurchaseOrder, the app figures out that you probably mean that one.
        5. Make an API call to the server to update the count and create a StockItem.

In this pullrequest I added/changed a bit in the code:
- Added order.dart to define InvenTreePO, InvenTreeSO, InvenTreePOLineItem, InvenTreeSOLineItem. (I want to check later if I can merge those classes a bit as there's a lot of similarity in them)
- Most changes happen to barcode.dart
- Added `== operator` and `hashCode()` to InvenTreeModel so it's possible to use in a `Set<>`

Please leave any feedback below as this is not completely done yet.

Kind regards,

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks @Guusggg this is top priority when I return from leave next week

**Comment by SchrodingersGat** [comment]
@Guusggg so sorry for the delay on this - I've finally got some free time to look at this now :)

**Comment by SchrodingersGat** [comment]
@Guusggg I'm putting together a clean framework for rendering purchase orders / etc over in #72 before integrating this one in

**Comment by Guusggg** [comment]
@SchrodingersGat Awesome, I've seen the commits that contain interesting messages ^^. I currently have no ideas to contribute but if you have something you need help with or long for, please tell me about it!

**Pull request closed without merging**
