### PR TITLE
Barcode Scanning Updates

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Closes https://github.com/inventree/inventree-app/pull/444
- Ref https://github.com/inventree/inventree-app/issues/446

Taking inspiration from linked issues, this PR adds two new barcode scanning features:

- Button to pause / resume barcode scanning
- Option for "single shot" or "continuous" barcode scanning with the camera

### CODE REVIEW

**Comment by Alex9779** [comment]
Going to check that out soon...

**Comment by wolflu05** [comment]
Could someone please summarize how this now works?

The idea I liked the most from the last discussions was to
1. short tap to pause/unpause somewhere. 
2. additionally if you tap and hold down scanning is paused until released.
3. there is a button to manually trigger a scan, just like you have a physical scanner in your hand
4. make configurable if you want to start with a paused scanner or a auto scanner.

**Comment by SchrodingersGat** [comment]
@wolflu05 that's basically it except for the "hold for continuous scan" has not been implemented.

**Comment by Alex9779** [comment]
Looks good to me though I am missing "hold to pause release to continue".
I aggree my implementation was primitive and unintuitive because you would have to read a manual to know that this exists, though I could tap and hold anywhere, now I have to explicitly push a button.
Considering my normal usage I will still have the barcode scanner start with continuous scanning because normally I scan a location or a code not in a matrix.
With this implementation I have to hit a button, target the code and hit the button again... This is all about reducing touches and reduce targeted touches.

Do you insist on a button?

WIth the indicator and text this is much better than what I did but would also work if the whole screen would act as a button.
Also "click to stop, click to continue" and "hold to stop, release to continue" would add a nice option...

**Comment by SchrodingersGat** [comment]
> Do you insist on a button?

I would at least like a visible user interface element which corresponds with the action being performed, not something "invisible" - could lead to confusion I think.

> Also "click to stop, click to continue" and "hold to stop, release to continue" would add a nice option...

Can certainly look at this as an option

**Comment by Alex9779** [comment]
What if you use the play pause icon as an indicator on top instead of the progress indicator? And then allow clicking anywhere and change the icon accordingly...

**Comment by SchrodingersGat** [comment]
@Alex9779 I have implemented based on your suggestion, I think it is pretty clean now. The icon is still there, but the touch input works on the whole screen area.

- In "single scan mode" it is tap to pause / tap to resume
- In "continuous scan mode" it is hold to pause / release to resume

**Comment by Alex9779** [comment]
I created #453 which allows tap and hold, this is what comes very close to what I want...

**Comment by SchrodingersGat** [comment]
@Alex9779 can you explain the differences between #453 and what is now implemented here?

**Comment by Alex9779** [comment]
Sure...
In your implementation a major issue for me was that when I moved my finger while holding the action was cancelled because of the event you used.
Also my implementation you have tap and hold working in both modes:

- In "continuous scan mode" it is tap to pause / tap to resume or hold to pause / release to resume
- In "single scan mode" it is tap to resume / tap to pause or hold to resume /release to pause

Though I think this is not exactly what @wolflu05 meant by "there is a button to manually trigger a scan, just like you have a physical scanner in your hand".
Maybe I misinterpreted the naming of the modes and just turned the way it works for "single scan mode". I thought it has something to do with the initial state of the scanner when you call it.
You changed that in your second push... I reverted that, but now I think this is not correct.
The problem here is that there is no real explanation in the settings, it is just "deactivated continuous scanning".
And what I also expect from a real "single scan mode" is that scanning is stopped after each succesful scan.

**Comment by Alex9779** [comment]
So what I think how it should work:

- the scanner should be active if you call it, no matter the setting you chose
- if "continuous scanning" is set then you should be able to toggle with taps or hold/release and after a successful scan the scanner stays active
- if "not-continuos scanning" is set aka "single scan mode" then you should be able to toggle with taps or hold/release and after a successful scan the scanner stops not matter if the user is still holding

But this need some more explanation IMHO in the settings...
And BTW my implementation does not do this...

**Comment by SchrodingersGat** [comment]
Ok so what you describe is pretty identical to what I have in this PR. There does need to be a separate PR to update the documentation around this

**Comment by Alex9779** [comment]
Ok sorry, so I tested your version right now again and here are my issues:

"Continuous Scannning" activated:

- tap to pause does not work, after releasing it continues right away
- just holding down pauses
- moving finger while holding also continues scanning

The "single scan mode" I think works as intended now I understood the process...

**Comment by SchrodingersGat** [comment]
Ok, both tap-to-pause and hold-to-pause are explicitly set by a separate user setting now

**Comment by Alex9779** [comment]
Ya this works.

Though IMHO a second settings is not necessary. My implementation demonstrated it is possible to combine both which allows more flexibility covering multiple use cases by just different gestures.
In your implementation you use the onTapDown event which I did too so this is possible. The engine chooses between a tap and a long press so and you can use the onLongPressEnd to unpause and the onTapDown to toggle.

I wouldn't argue this way if you'd use the onTap event which would only perform its action after a real tap with release...

But I don't wanna be picky, if that's the way you like it...

**Comment by SchrodingersGat** [comment]
@Alex9779 I think I finally get what you mean. The new implementation is a lot simpler without an extra setting.

**Pull request merged**
