### PR TITLE
insert image from pasteboard

### PR DESCRIPTION
**Pull request by Alex9779**
This has issues:

- does not work with an object extracted from a picture
- portrait photos not modified will become landscape
- the process takes some time but no progress is displayed, just when the picture is loaded again from the server

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
> The process takes some time but no progress is displayed, just when the picture is loaded again from the server

We can add a "loading overlay" to indicate that the app is busy talking to the server:

https://github.com/inventree/inventree-app/blob/40fad26c06d68b86965871e98569df2445ddc4d2/lib/api_form.dart#L915C10-L915C10

**Comment by Alex9779** [comment]
Strange, I tried it again and now it works for an extracted object...
Wanted to record a video and surprise...

**Comment by Alex9779** [comment]
https://github.com/inventree/inventree-app/assets/6394581/29db33e6-88c9-4e8c-bcbf-8b14fc181465

**Comment by Alex9779** [comment]
BTW getting a temp path I found two options:

1. using path_provider package and getTemporaryDirectory()
2. Directory.systemTemp.path

I tried both and both seem to work though I didn't check the paths I get out of them... You have any idea which is better or are there any differences?

**Comment by SchrodingersGat** [comment]
> BTW getting a temp path I found two options:
> 
> 1. using path_provider package and getTemporaryDirectory()
> 2. ${Directory.systemTemp.path}
> 
> I tried both and both seem to work though I didn't check the paths I get out of them... You have any idea which is better or are there any differences?

Option 1 feels cleaner to me?

**Comment by Alex9779** [comment]
> Option 1 feels cleaner to me?

Really? This is an extra package and you need an import, the other is straight from Flutter SDK it seems...

**Comment by Alex9779** [comment]
pushed and update, used the random package to generate a random file name because I had problems using the same over and over again but forgot to use it again when prepapring the PR...

**Comment by Alex9779** [comment]
and now it is not working again with copied objects... maybe the random file names are a problem? But without I have problems that the app is not changing the pictures though the new is uploaded to the server the app still displays the old and never displays the new...

**Comment by Alex9779** [comment]
Hmmm seems to be an issue with the photos app, I killed it and tried it again and now it works again...

**Comment by SchrodingersGat** [comment]
> > Option 1 feels cleaner to me?
> 
> Really? This is an extra package and you need an import, the other is straight from Flutter SDK it seems...

we already use `path_provider`:

https://github.com/inventree/inventree-app/blob/40fad26c06d68b86965871e98569df2445ddc4d2/pubspec.yaml#L38

**Comment by Alex9779** [comment]
yes, but not in this file...

An other major issue is that the pasteboard package does not work with Android, super_clipboard claims to do so...

**Comment by SchrodingersGat** [comment]
A library that supports both platforms would be ideal

**Comment by Alex9779** [comment]
> A library that supports both platforms would be ideal

Yup, but I am not able to get another working. "super_clipboard" is totally different to handle and I have no idea to to deal with it.

Also I think a picture compression would be good because copied picutres (full or extracted objects) from the camera roll tend to be multiple megabytes.
And this implies some kind of setting how to deal with that, size of the picture, resolution, ..., and honestly this is out of my reach at the moment...

**Comment by Alex9779** [comment]
I learned a lot from the barcode scanner PR but this has not a so high priority for me atm.
So I am closing though I will continue to work on this within the next weeks or so...
When I got some results, I will open a new PR...

**Pull request closed without merging**
